name = "IRP Land Rover Defender 110";
picture = "CrSk_Land_Rover_Defender_110/logos/modIcon.paa";
logoSmall = "CrSk_Land_Rover_Defender_110/logos/modIconSmall.paa";
logo = "CrSk_Land_Rover_Defender_110/logos/modIconSmall.paa";
logoOver = "CrSk_Land_Rover_Defender_110/logos/mocIcon.paa";
tooltip = "IRP Land Rover Defender 110 by CrushingSkirmish";
overview = "By CrushingSkirmish. The new Land Rover Defender will make travelling around the lands Chernarus feel like breeze and of course, with a big boot and the rooftop you will have plenty of extra space for when you are moving equipment. As with the real landrover the battery is attached on the driver seat. The Land Rover comes in many variants to fit everyone needs! https://www.ForsakenRP.com/";
action = "https://steamcommunity.com/sharedfiles/filedetails/?id=1912237302";
author = "CrushingSkirmish";
version = "ver.05.02.21";