name = "ToxicZone";
author = "TheDmitri";
version = "1.5.0";
overview = "ToxicZone Mod (SP/MP)"; 	// description
action = "https://dmitridayzmodding.jimdosite.com";		// link
tooltip = "ToxicZone";
picture = "ToxicZone_Data/imagesets/ToxicZoneLogo.edds";			// picture in expanded description
logoSmall = "ToxicZone_Data/imagesets/ToxicZoneLogo.edds";	// icon next to mod name when description is not expanded
logo = "ToxicZone_Data/imagesets/ToxicZoneLogo.edds";				// logo below game menu
logoOver = "ToxicZone_Data/imagesets/ToxicZoneLogo.edds";							// over